# Generated by Django 5.1.2 on 2024-10-18 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="products",
            new_name="product",
        ),
    ]
